import type { ScopeGraph } from '@/lib/api-client'

/**
 * A small graph with the same shape as /api/scope: two releases, two phases,
 * one populated cell, one cell with capabilities but no features, and one
 * genuinely empty cell.
 */
export function makeScopeGraph(overrides: Partial<ScopeGraph> = {}): ScopeGraph {
  const graph: ScopeGraph = {
    overrides: [],
    releases: [
      {
        id: '1.1',
        label: 'Release 1.1',
        name: 'Pilot',
        description: '',
        display_order: 1,
        in_mapping_source: 1,
        in_sequencing_source: 1,
        source: 'both',
      },
      {
        id: '1.4',
        label: 'Release 1.4',
        name: '',
        description: '',
        display_order: 2,
        in_mapping_source: 0,
        in_sequencing_source: 1,
        source: 'sequencing',
      },
    ],
    phases: [
      {
        id: 'access-and-onboarding',
        name: 'Access & Onboarding',
        epic_ref: '179',
        epic_description: 'Employer registration',
        display_order: 1,
        source: 'mapping',
      },
      {
        id: 'manage-vacancies',
        name: 'Manage Vacancies',
        epic_ref: '177',
        epic_description: 'Create and manage vacancies',
        display_order: 2,
        source: 'mapping',
      },
    ],
    pwcFeatures: [
      {
        id: 'F-001',
        name: 'Invite employer',
        foundational_build: '',
        release_id: '1.1',
        phase_id: 'access-and-onboarding',
        source_phase_label: 'Onboarding via invite',
        capability_note: null,
        display_order: 1,
        source: 'mapping',
      },
      {
        id: 'F-002',
        name: 'Verify employer',
        foundational_build: '',
        release_id: '1.1',
        phase_id: 'access-and-onboarding',
        source_phase_label: 'Access & onboarding',
        capability_note: null,
        display_order: 2,
        source: 'mapping',
      },
    ],
    assumptions: [],
    mvpFeatures: [
      { id: 1, ref: 938, scope_option: '1A', title: 'Additional users', source: 'mapping' },
      { id: 2, ref: 938, scope_option: null, title: 'Additional users', source: 'mapping' },
      { id: 3, ref: 948, scope_option: '1B', title: 'Verification methods', source: 'mapping' },
    ],
    capabilities: [
      {
        id: 10,
        mvp_feature_id: 2,
        mvp_ref: 938,
        mvp_owner_ambiguous: 1,
        text: 'Invite employer to register',
        actor: 'staff',
        release_id: '1.1',
        phase_id: 'access-and-onboarding',
        source_phase_label: 'Onboarding via invite',
        source: 'both',
      },
      {
        id: 11,
        mvp_feature_id: 2,
        mvp_ref: 938,
        mvp_owner_ambiguous: 1,
        text: 'Receive secure email invite',
        actor: 'employer',
        release_id: '1.1',
        phase_id: 'access-and-onboarding',
        source_phase_label: 'Onboarding via invite',
        source: 'both',
      },
      {
        id: 12,
        mvp_feature_id: 3,
        mvp_ref: 948,
        mvp_owner_ambiguous: 0,
        text: 'Electronic T&Cs acceptance',
        actor: 'employer',
        // Placed in a release with no features — the 1.4 case (R-8.5).
        release_id: '1.4',
        phase_id: 'manage-vacancies',
        source_phase_label: 'Manage Vacancies',
        source: 'sequencing',
      },
    ],
    featureMvpLinks: [
      { pwc_feature_id: 'F-001', mvp_feature_id: 1, source: 'mapping' },
      { pwc_feature_id: 'F-001', mvp_feature_id: 2, source: 'mapping' },
      { pwc_feature_id: 'F-002', mvp_feature_id: 3, source: 'mapping' },
    ],
    featureCapabilityLinks: [
      {
        id: 100,
        pwc_feature_id: 'F-001',
        capability_id: 10,
        source_citations: 1,
        matched: 1,
        release_conflict: 0,
        phase_conflict: 0,
        feature_release_id: null,
        capability_release_id: null,
        feature_phase_label: null,
        capability_phase_label: null,
        phase_conflict_merged: 0,
        resolution_state: 'unreviewed',
        resolution_note: null,
        resolved_at: null,
        source: 'mapping',
      },
      {
        id: 101,
        pwc_feature_id: 'F-001',
        capability_id: 11,
        source_citations: 1,
        matched: 1,
        release_conflict: 0,
        // A phase conflict the canonical merge resolves — not a finding.
        phase_conflict: 1,
        feature_release_id: null,
        capability_release_id: null,
        feature_phase_label: 'Access & onboarding',
        capability_phase_label: 'Onboarding via invite',
        phase_conflict_merged: 1,
        resolution_state: 'unreviewed',
        resolution_note: null,
        resolved_at: null,
        source: 'mapping',
      },
      {
        id: 102,
        pwc_feature_id: 'F-002',
        capability_id: 12,
        source_citations: 1,
        matched: 0,
        release_conflict: 1,
        phase_conflict: 1,
        feature_release_id: '1.1',
        capability_release_id: '1.4',
        feature_phase_label: 'Access & onboarding',
        capability_phase_label: 'Manage Vacancies',
        phase_conflict_merged: 0,
        resolution_state: 'unreviewed',
        resolution_note: null,
        resolved_at: null,
        source: 'mapping',
      },
    ],
    counts: {
      releases: 2,
      phases: 2,
      pwcFeatures: 2,
      assumptions: 0,
      mvpFeatures: 3,
      capabilities: 3,
      featureMvpLinks: 3,
      featureCapabilityEdges: 3,
      featureCapabilityCitations: 3,
      releaseConflicts: 1,
      phaseConflicts: 2,
      unresolvedConflicts: 2,
      unmatchedLinks: 1,
    },
  }
  return { ...graph, ...overrides }
}
