-- A question someone has raised about a PwC feature.
--
-- Capabilities have carried one since 006; features could not, so a question
-- about a feature had to be attached to one of its capabilities or written
-- down somewhere else. It is the same kind of open item — a person flagging
-- something that needs an answer, not a disagreement between the two source
-- documents — and it wants the same visibility.
--
-- Like the capability's, it stays out of the conflict counts on purpose.
-- Those are the drift baseline between the two documents, and a question is
-- neither document's.
--
-- SQLite has no ADD COLUMN IF NOT EXISTS. Adding a nullable column is the
-- normal way to extend a table, and the runner applies this once.
ALTER TABLE pwc_features ADD COLUMN question TEXT;
