-- A question someone has raised about an MSD feature record.
--
-- Capabilities have carried one since 006 and PwC features since 009. An MSD
-- feature is the third thing on the map someone reads and wants to ask about,
-- and until now the question had to be hung off one of its capabilities —
-- which attributes it to the wrong record, and loses it entirely for the five
-- records that own no capability.
--
-- Like the other two, it stays out of the conflict counts on purpose. Those
-- are the drift baseline between the two source documents; a question is a
-- person flagging something for an answer, which is neither document's.
--
-- SQLite has no ADD COLUMN IF NOT EXISTS. Adding a nullable column is the
-- normal way to extend a table, and the runner applies this once.
ALTER TABLE mvp_features ADD COLUMN question TEXT;
